name: .NET Core

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Set up Cosmos DB environment variables
      run: |
        echo "COSMOS_DB_ACCOUNT=${{ secrets.COSMOS_DB_ACCOUNT }}" >> $GITHUB_ENV
        echo "COSMOS_DB_KEY=${{ secrets.COSMOS_DB_KEY }}" >> $GITHUB_ENV
        echo "COSMOS_DB_DATABASE_NAME=${{ secrets.COSMOS_DB_DATABASE_NAME }}" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: |
        dotnet publish -c Release -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app  # Nombre del artefacto
        path: ./publish  # Ruta del artefacto

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: dotnet-app  # Nombre debe coincidir
        path: ./artifacts

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'predicciontinka'
        slot-name: 'Production'
        package: .
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3b4947a110ec4a0ea1d28f4f92e2fef3 }}
